import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
import {createHash,randomUUID} from 'node:crypto';
import {assertCompanionAcceptance} from '../src/companion-acceptance.mjs';
import {createCoreEngineAdapter,collectCoreSourcePins,hostProofContent} from '../src/core-engine-adapter.mjs';

// The core snapshot below is generated by the pinned vendored core fixture in a
// fresh test directory. Model/native/host receipts are synthetic pure fixtures;
// these tests do not make inference or reach the real Commander endpoint.
const base=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
// Fresh test-owned short root; no production database or Windows policy change.
// Resolve the existing hosted TEMP junction before creating test-owned state.
const area=fs.mkdtempSync(path.join(fs.realpathSync.native(os.tmpdir()),'commander-policy-tests-'));
if(path.join(area,'acceptance-owned-'+'0'.repeat(36),'.engine/project-engine/project-runs.sqlite-journal').length>=240)throw Error('TEST_TEMP_PATH_TOO_LONG');
const target=path.join(area,'acceptance-owned-'+randomUUID());fs.mkdirSync(target);
const coreRoot=path.join(base,'fixtures/core-v0.10.6');
const configSha256='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
const content=hostProofContent(configSha256),hash=value=>createHash('sha256').update(value).digest('hex'),proofSha256=hash(content);
const ticks=[],actions=[];
const adapter=await createCoreEngineAdapter({coreRoot,corePins:collectCoreSourcePins(coreRoot),root:target,
  enrollment:{id:'acceptance-proof',runId:'acceptance-run',owner:'saeed',authorizationSha256:'a'.repeat(64),configSha256,
    planDefinitions:[{id:'observe_status',tool:'system_status',arguments:{}},
      {id:'write_proof',tool:'write_text',arguments:{path:'HOST_PROOF.json',content}}]},
  planner:{plan:async()=>({choice:'CONTINUE_STEP'})},
  dispatch:async(name,args)=>{
    if(name==='system_status'){
      actions.push({tool:name,responseSha256:'b'.repeat(64),requestClosed:true});
      return {status:{name:'chatgpt-remote-commander',deviceName:'saeid',platform:'win32',version:'0.10.6',configSha256,
        instance:{profile:'default',isolated:false}}};
    }
    fs.writeFileSync(path.join(target,args.path),args.content,{flag:'wx'});actions.push({tool:name,path:args.path,sha256:proofSha256});
    return {path:path.join(target,args.path),sha256:proofSha256,bytes:Buffer.byteLength(content)};
  }});
let sample;
try{
  await adapter.enroll();for(let n=0;n<3;n++)ticks.push(await adapter.tick());
  const [coreStatus,state,operations]=await Promise.all([adapter.status(),adapter.state(),adapter.operations()]);
  const modelRecords=[1,2].map(call=>({schema:1,status:'PASS_MODEL_PROPOSAL_VALIDATED',call,model:'gpt-6.1-sol',threadId:randomUUID(),
    usage:{input_tokens:1200,output_tokens:10,cached_input_tokens:0},choice:'CONTINUE_STEP',streamSha256:'c'.repeat(64),artifactSha256:'d'.repeat(64),
    nativeProof:{schema:1,status:'COMPLETED',win32Error:0,cleanupWin32Error:0,cleanupConfirmed:true,pid:7000+call,
      creationFileTime:'134038077025746660',assignedBeforeResume:true,exitCode:0,elapsedMs:5000,activeJobProcesses:0,
      peakJobMemoryBytes:100*1048576,ownedJobTerminated:false,stdoutHex:'7b7d',stderrHex:''},knownDiagnostic:1,automaticRetry:false}));
  sample={coreStatus,state,operations,ticks,modelRecords,actions,proofSha256,expectedProofSha256:proofSha256};
  fs.writeFileSync(path.join(target,'PURE_ACCEPTANCE_FIXTURE.json'),JSON.stringify({scope:'MOCK_MODEL_AND_HOST_NO_REAL_NATIVE_EXECUTION',sample},null,2),{flag:'wx'});
}finally{await adapter.close();}

test('pinned core fixture requires FINAL_ACCEPTED, not file-exists or model-exit alone',()=>{
  const accepted=assertCompanionAcceptance(sample);assert.equal(accepted.phase,'FINAL_ACCEPTED');
  assert.equal(accepted.status,'PASS_FINITE_COMPANION_ACCEPTANCE');assert.equal(accepted.whole,'NOT_FINAL');
  assert.equal(accepted.modelCalls,2);assert.equal(accepted.actions,2);assert.equal(accepted.proofSha256,proofSha256);
  assert.equal(sample.state.acceptanceStatus,'UNVALIDATED','this wrapper label is not finalized authority');
  assert.equal(sample.state.state.acceptanceStatus,'PASS');
});
const cases=[
  ['core remains BLOCKED',s=>{s.coreStatus.status='BLOCKED';}],
  ['reverified alternative is not this fresh completion',s=>{s.coreStatus.lastCode='PROJECT_ACCEPTANCE_REVERIFIED';}],
  ['max action budget expanded',s=>{s.coreStatus.maxActions=3;}],
  ['provider budget reset',s=>{s.coreStatus.plannerCalls=1;}],
  ['extra model allowance',s=>{s.coreStatus.maxPlannerCalls=3;}],
  ['pending uncertain worker',s=>{s.coreStatus.pendingWorker={status:'RESERVED'};}],
  ['checks made model editable',s=>{s.coreStatus.checksArePlannerEditable=true;}],
  ['last tick was not final',s=>{s.ticks[2].status='QUEUED';}],
  ['missing middle tick',s=>{s.ticks.splice(1,1);}],
  ['final status differs from final tick',s=>{s.coreStatus.summary='contradictory snapshot';}],
  ['postdeadline completion',s=>{s.coreStatus.updatedAt=new Date(s.coreStatus.deadline+1).toISOString();}],
  ['verifier reports false',s=>{s.coreStatus.verification[0].passed=false;}],
  ['wrong proof hash',s=>{s.proofSha256='f'.repeat(64);}],
  ['workflow still FINALIZING',s=>{s.state.state.lifecycleState='FINALIZING';}],
  ['workflow finalization UNVALIDATED',s=>{s.state.state.finalization.status='UNVALIDATED';}],
  ['false acceptance criterion',s=>{s.state.state.finalization.acceptanceResults=[false];}],
  ['paused control',s=>{s.state.state.control.intent='PAUSED';}],
  ['automatic scheduler secretly enabled',s=>{s.state.state.scheduler.enabled=true;}],
  ['workflow final revision drift',s=>{s.state.state.revision++;}],
  ['wrong finalized evidence',s=>{s.state.state.finalization.evidence[0].sha256='f'.repeat(64);}],
  ['brain projection hash mismatch',s=>{s.state.state.brain.lastSyncSha256='f'.repeat(64);}],
  ['unknown workflow_get wrapper member',s=>{s.state.approved=true;}],
  ['uncertain write operation',s=>{s.operations.operations[1].status='UNCERTAIN';}],
  ['wrong journal workflow id',s=>{s.operations.id='another-workflow';}],
  ['wrong operation id',s=>{s.operations.operations[1].operationId=randomUUID();}],
  ['receipt belongs to different arguments',s=>{s.state.state.steps[1].receipt.inputHash='f'.repeat(64);}],
  ['history still planning',s=>{s.coreStatus.history[1].status='PLANNING';}],
  ['duplicate operations',s=>{s.operations.operations.push(s.operations.operations[1]);}],
  ['model STOP instead of continue',s=>{s.modelRecords[1].choice='STOP';}],
  ['replayed model thread',s=>{s.modelRecords[1].threadId=s.modelRecords[0].threadId;}],
  ['unknown model-generated action',s=>{s.modelRecords[0].tool='run_shell';}],
  ['retry flag enabled',s=>{s.modelRecords[0].automaticRetry=true;}],
  ['native cleanup unconfirmed',s=>{s.modelRecords[1].nativeProof.cleanupConfirmed=false;}],
  ['native descendants remain',s=>{s.modelRecords[0].nativeProof.activeJobProcesses=1;}],
  ['native was terminated',s=>{s.modelRecords[1].nativeProof.ownedJobTerminated=true;}],
  ['native root failed',s=>{s.modelRecords[1].nativeProof.exitCode=1;}],
  ['native process not assigned before execution',s=>{s.modelRecords[1].nativeProof.assignedBeforeResume=false;}],
  ['native memory limit exceeded',s=>{s.modelRecords[1].nativeProof.peakJobMemoryBytes=513*1048576;}],
  ['request close not confirmed',s=>{s.actions[0].requestClosed=false;}],
  ['write action goes elsewhere',s=>{s.actions[1].path='../unknown.txt';}],
  ['extra host effect',s=>{s.actions.push({tool:'run_shell'});}]
];
for(const [name,mutate]of cases)test('acceptance denies '+name,()=>{
  const changed=structuredClone(sample);mutate(changed);assert.throws(()=>assertCompanionAcceptance(changed));
});
test('acceptance rejects getter without evaluating it',()=>{
  const changed=structuredClone(sample);let evaluated=false;
  Object.defineProperty(changed.coreStatus,'status',{enumerable:true,get(){evaluated=true;return 'COMPLETED';}});
  assert.throws(()=>assertCompanionAcceptance(changed),{code:'COMPANION_ACCEPTANCE_DATA'});assert.equal(evaluated,false);
});
test('acceptance refuses unknown critical run field',()=>{
  const changed=structuredClone(sample);changed.coreStatus.phase='FINAL_ACCEPTED';
  assert.throws(()=>assertCompanionAcceptance(changed),{code:'COMPANION_ACCEPTANCE_SCHEMA'});
});
