// Public export: the old-choice event fixture is synthetic, not a real-model transcript.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateEvents,validateProposal,validateModelResult,knownDiagnostic,argumentsFor,childEnv,MODEL,disabledFeatures}from'../src/model-contract.mjs';

const start={type:'thread.started',thread_id:'12345678-1234-5678-9012-123456789012'},turn={type:'turn.started'},message={type:'item.completed',item:{id:'item_1',type:'agent_message',text:'{"choice":"CONTINUE_STEP"}'}},end={type:'turn.completed',usage:{input_tokens:1,cached_input_tokens:0,output_tokens:1}},warning={type:'item.completed',item:{id:'item_0',type:'error',message:knownDiagnostic}};
const encode=items=>items.map(JSON.stringify).join('\n')+'\n';
const fixture=(items=[start,turn,message,end],artifact='{"choice":"CONTINUE_STEP"}')=>({stdout:encode(items),artifact,exitCode:0,signal:null,stderr:'',overflow:false,pipeError:null});
test('valid strict model result provides exact proposal and pending admission, not authority',()=>{const proof=validateModelResult(fixture());assert.equal(proof.proposal.choice,'CONTINUE_STEP');assert.equal(proof.decision,'PROPOSAL_REQUIRES_OWNER_EXECUTOR_ADMISSION');assert.equal(proof.toolsEnabled,false);assert.ok(Object.isFrozen(proof.proposal));});
test('STOP is valid and preserved without action',()=>{const m={...message,item:{...message.item,text:'{"choice":"STOP"}'}};assert.equal(validateModelResult(fixture([start,turn,m,end],'{"choice":"STOP"}')).decision,'STOP_NO_ACTION');});
test('artifact parity rejects stream STOP/file CONTINUE_STEP and inverse',()=>{const m={...message,item:{...message.item,text:'{"choice":"STOP"}'}};assert.throws(()=>validateModelResult(fixture([start,turn,m,end])));assert.throws(()=>validateModelResult(fixture(undefined,'{"choice":"STOP"}')));});
test('synthetic old-choice stream is denied; fixture layout is valid for new-choice only',()=>{const raw=JSON.parse(fs.readFileSync(new URL('./fixtures/synthetic-old-model-result.json',import.meta.url)));const proof={stdout:raw.stdout,artifact:'{"choice":"OBSERVE_STATUS"}',exitCode:raw.code,signal:raw.signal,stderr:raw.stderr,overflow:raw.overflow,pipeError:raw.pipeError};assert.throws(()=>validateModelResult(proof));const rows=raw.stdout.trim().split('\n').map(JSON.parse);for(const row of rows)if(row.item?.type==='agent_message')row.item.text='{"choice":"CONTINUE_STEP"}';const accepted=validateModelResult({...proof,stdout:encode(rows),artifact:'{"choice":"CONTINUE_STEP"}'});assert.equal(accepted.knownDisabledToolDiagnostic,1);assert.equal(accepted.proposal.choice,'CONTINUE_STEP');});
for(const [name,items]of [
 ['no turn',[start,message,end]],['duplicate turn',[start,turn,turn,message,end]],['message before turn',[start,message,turn,end]],['thread missing ID',[{type:'thread.started'},turn,message,end]],['thread extra fields',[{...start,hiddenTool:{}},turn,message,end]],['item before thread',[message,start,turn,end]],['duplicate thread',[start,start,turn,message,end]],['no completion',[start,turn,message]],['event after complete',[start,turn,message,end,turn]],['multiple proposals',[start,turn,message,message,end]],['reasoning after final',[start,turn,message,{type:'item.completed',item:{id:'item_2',type:'reasoning',text:'later'}},end]],['unknown event',[start,turn,{type:'tool.call',item:{}},message,end]],['extra message fields',[start,turn,{...message,item:{...message.item,path:'x'}},end]],['incomplete item',[start,turn,{type:'item.started',item:{id:'item_2',type:'reasoning',text:''}},message,end]],['reasoning empty identity',[start,turn,{type:'item.completed',item:{id:'',type:'reasoning',text:'x'}},message,end]],['reasoning type changed',[start,turn,{type:'item.started',item:{id:'item_2',type:'reasoning',text:''}},{type:'item.completed',item:{id:'item_2',type:'agent_message',text:'{"choice":"OBSERVE_STATUS"}'}},end]],
 ])test('rejects '+name,()=>assert.throws(()=>validateEvents(encode(items))));
for(const kind of ['command_execution','mcp_tool_call','file_change','web_search','error','image_generation','browser_use'])test('denies actual tool/error '+kind,()=>assert.throws(()=>validateEvents(encode([start,turn,{type:'item.completed',item:{id:'item_2',type:kind,text:'{}'}},message,end]))));
test('optional exact preturn diagnostic accepted once only',()=>{assert.equal(validateEvents(encode([start,warning,turn,message,end])).knownDisabledToolDiagnostic,1);for(const items of [[start,warning,warning,turn,message,end],[start,turn,warning,message,end],[warning,start,turn,message,end],[start,{...warning,item:{...warning.item,message:knownDiagnostic+' '}},turn,message,end],[start,warning,turn,{...message,item:{...message.item,id:'item_0'}},end]])assert.throws(()=>validateEvents(encode(items)));});
for(const [name,value]of [['scalar',1],['array',[]],['null',null],['negative',{input_tokens:-1,output_tokens:1}],['decimal',{input_tokens:1.5,output_tokens:1}],['unknown',{input_tokens:1,output_tokens:1,total:2}],['missing',{input_tokens:1}],['cached greater than total',{input_tokens:1,cached_input_tokens:2,output_tokens:1}],['reasoning greater than total',{input_tokens:1,output_tokens:1,reasoning_output_tokens:2}],['output bound',{input_tokens:1,output_tokens:4097}],['input bound',{input_tokens:1000001,output_tokens:1}]])test('usage rejects '+name,()=>assert.throws(()=>validateEvents(encode([start,turn,message,{...end,usage:value}]))));
test('reasoning start/completion followed by one final message is valid',()=>{const a={type:'item.started',item:{id:'item_2',type:'reasoning',text:''}},b={type:'item.completed',item:{id:'item_2',type:'reasoning',text:'bounded reasoning'}};assert.equal(validateEvents(encode([start,turn,a,b,message,end])).messages,1);});
test('proposal rejects duplicates, escaped duplicate keys, malformed schema and unbounded input',()=>{for(const text of ['{"choice":"STOP","choice":"OBSERVE_STATUS"}','{"choice":"STOP","\\u0063hoice":"OBSERVE_STATUS"}','{"choice":"RUN"}','{"choice":"STOP","extra":1}','[]','null','{"choice":{}}',' '.repeat(1025)+'{"choice":"STOP"}'])assert.throws(()=>validateProposal(text));});
test('event count/line/depth/UTF16 validity are bounded',()=>{for(const text of ['','\n'+encode([start,turn,message,end]),encode([start,turn,message,end])+ '\n',encode([start,turn,message,end]).repeat(17),encode([start,turn,{...message,item:{...message.item,text:'x'.repeat(40000)}},end]),'\ud800'])assert.throws(()=>validateEvents(text));});
for(const [key,value]of [['exitCode',1],['signal','SIGTERM'],['stderr','unexpected'],['overflow',true],['pipeError','EPIPE']])test('process proof rejects '+key,()=>assert.throws(()=>validateModelResult({...fixture(),[key]:value})));
test('process result rejects extra authority-bearing keys and accessors',()=>{assert.throws(()=>validateModelResult({...fixture(),allowAction:true}));const v=fixture();Object.defineProperty(v,'stdout',{get(){throw Error('must not execute');},enumerable:true});assert.throws(()=>validateModelResult(v));});
test('arguments pin existing model, disable actions, keep rules, and read-only sandbox',()=>{const args=argumentsFor('C:\\Commander\\owned');assert.equal(args[args.indexOf('--model')+1],MODEL);assert.equal(args[args.indexOf('--sandbox')+1],'read-only');assert.ok(!args.includes('--ignore-rules'));for(const flag of disabledFeatures)assert.ok(args.includes(flag));assert.ok(Object.isFrozen(args));});
test('argument path rejects relative/UNC/ADS/ambiguous roots',()=>{for(const root of ['relative','C:\\Commander\\..\\owned','\\\\host\\share\\owned','C:\\owned:ads','C:\\owned"','C:\\owned\n'])assert.throws(()=>argumentsFor(root));});
test('environment removes paid API/secrets/node injection while preserving existing login location',()=>{const out=childEnv({SystemRoot:'C:\\Windows',CODEX_HOME:'C:\\existing-login',OPENAI_API_KEY:'not-read',AZURE_OPENAI_API_KEY:'not-read',CODEX_ACCESS_TOKEN:'not-read',COMMANDER_TOKEN:'not-read',NODE_OPTIONS:'--require bad',NODE_PATH:'bad'});assert.deepEqual(out,{SystemRoot:'C:\\Windows',CODEX_HOME:'C:\\existing-login',NODE_OPTIONS:'',NODE_PATH:''});});
test('environment rejects accessor/proxy without reading them',()=>{const obj={};Object.defineProperty(obj,'OPENAI_API_KEY',{get(){throw Error('must not execute');},enumerable:true});assert.throws(()=>childEnv(obj));assert.throws(()=>childEnv(new Proxy({},{ownKeys(){throw Error('must not execute');}})));});
