import Gio from 'gi://Gio';
import GLib from 'gi://GLib';
import Meta from 'gi://Meta';
import Shell from 'gi://Shell';
import * as Main from 'resource:///org/gnome/shell/ui/main.js';
import {Extension} from 'resource:///org/gnome/shell/extensions/extension.js';

const IFACE = `<node><interface name="org.gnome.Shell.Extensions.ChatGPTRemoteCommander"><method name="Invoke"><arg type="s" direction="in" name="request"/><arg type="s" direction="out" name="response"/></method></interface></node>`;
const STOP_PATH=GLib.build_filenamev([GLib.get_user_state_dir(),'chatgpt-remote-commander','GUI_STOP']);
const TOKEN_PATH=GLib.build_filenamev([GLib.get_user_config_dir(),'chatgpt-remote-commander','gui-extension-token']);
const sleep=ms=>new Promise(resolve=>GLib.timeout_add(GLib.PRIORITY_DEFAULT,Math.max(1,ms),()=>{resolve();return GLib.SOURCE_REMOVE;}));
const fail=code=>{throw new Error(code);};
class Service {
  constructor(){this._destroyed=false;this._token='';try{const[ok,bytes]=GLib.file_get_contents(TOKEN_PATH);if(ok)this._token=new TextDecoder().decode(bytes).trim();}catch(_) {}}
  destroy(){this._destroyed=true;this._token='';}
  _authorized(req){if(this._destroyed)fail('GUI_EXTENSION_DISABLED');if(!this._token||typeof req.auth!=='string'||req.auth.length<32||req.auth!==this._token)fail('GUI_EXTENSION_AUTH_FAILED');}
  _stopped(req=null){if(this._destroyed)return true;if(Gio.File.new_for_path(STOP_PATH).query_exists(null))return true;const requested=req?.stopFile;return typeof requested==='string'&&requested.endsWith('/var/GUI_STOP')&&Gio.File.new_for_path(requested).query_exists(null);}

  _screens(){const monitors=Main.layoutManager.monitors??[],primary=Main.layoutManager.primaryIndex??0,screens=[];for(let i=0;i<monitors.length;i++){const g=monitors[i];screens.push({index:i,left:g.x,top:g.y,width:g.width,height:g.height,primary:i===primary});}return screens;}
  _windowHandle(w){if(!w)return'0';try{const id=w.get_id();if(Number.isSafeInteger(id)&&id>0)return String(id);}catch(_){}try{const id=w.get_stable_sequence();if(Number.isSafeInteger(id)&&id>0)return String(id);}catch(_){}return'0';}
  _windowRecord(w){if(!w)return{handle:'0',title:'',processId:0,wmClass:'',focused:false};let pid=0,title='',wmClass='';try{pid=Number(w.get_pid())||0;}catch(_){}try{title=w.get_title()??'';}catch(_){}try{wmClass=w.get_wm_class()??'';}catch(_){}return{handle:this._windowHandle(w),title,processId:Number.isSafeInteger(pid)?pid:0,wmClass,focused:global.display.focus_window===w};}
  _rawWindows(){const seen=new Set(),out=[];for(const actor of global.get_window_actors()){const w=actor.meta_window??actor.get_meta_window?.();if(!w)continue;const h=this._windowHandle(w);if(h==='0'||seen.has(h))continue;seen.add(h);out.push(w);}return out;}
  _snapshot(screenIndex){const screen=this._screens().find(s=>s.index===screenIndex);if(!screen)fail('GUI_MONITOR_RANGE');const f=this._windowRecord(global.display.focus_window);let workspace=-1;try{workspace=global.workspace_manager.get_active_workspace_index();}catch(_){}return{screenIndex,bounds:{left:screen.left,top:screen.top,width:screen.width,height:screen.height},foreground:f.title,processId:f.processId,handle:f.handle,wmClass:f.wmClass,workspace};}
  _sameSnapshot(a,b){if(!a||!b||!a.bounds||!b.bounds)return false;for(const k of ['left','top','width','height'])if(a.bounds[k]!==b.bounds[k])return false;return a.screenIndex===b.screenIndex&&String(a.handle??'')===String(b.handle??'')&&String(a.foreground??'')===String(b.foreground??'')&&Number(a.processId??0)===Number(b.processId??0)&&Number(a.workspace??-1)===Number(b.workspace??-1);}
  _guard(req){if(this._stopped(req))fail('GUI_LOCAL_STOP');const expected=req.expected;if(!expected||!Number.isInteger(expected.screenIndex))fail('GUI_EXPECTED_FRAME_INVALID');const current=this._snapshot(expected.screenIndex);if(!this._sameSnapshot(expected,current))fail('GUI_FOREGROUND_OR_GEOMETRY_CHANGED');return current;}
  _focusTimestamp(){let ts=0;try{ts=Number(global.display.get_current_time_roundtrip());}catch(_){}if(!Number.isInteger(ts)||ts<=0)try{ts=Number(global.display.get_current_time());}catch(_){}if(!Number.isInteger(ts)||ts<=0)try{ts=Number(global.get_current_time());}catch(_){}if(!Number.isInteger(ts)||ts<=0)fail('GUI_FOCUS_TIMESTAMP_UNAVAILABLE');return ts;}
  async _screenshot(req){if(this._stopped(req))fail('GUI_LOCAL_STOP');const screenIndex=Number.isInteger(req.screenIndex)?req.screenIndex:0,before=this._snapshot(screenIndex),b=before.bounds;if(b.width<1||b.height<1||b.width*b.height>33554432)fail('GUI_CAPTURE_GEOMETRY_LIMIT');const dir=GLib.build_filenamev([GLib.get_user_runtime_dir(),'chatgpt-remote-commander','gui']);GLib.mkdir_with_parents(dir,0o700);const filename=GLib.build_filenamev([dir,`shot-${GLib.uuid_string_random()}.png`]),file=Gio.File.new_for_path(filename),stream=file.replace(null,false,Gio.FileCreateFlags.REPLACE_DESTINATION,null),shot=new Shell.Screenshot();const ok=await new Promise((resolve,reject)=>{shot.screenshot_area(b.left,b.top,b.width,b.height,stream,(obj,res)=>{try{const result=obj.screenshot_area_finish(res);resolve(Array.isArray(result)?result[0]===true:result===true);}catch(e){reject(e);}});});try{stream.close(null);}catch(_){}if(!ok){try{file.delete(null);}catch(_){}fail('GUI_CAPTURE_FAILED');}const after=this._snapshot(screenIndex);if(!this._sameSnapshot(before,after)){try{file.delete(null);}catch(_){}fail('GUI_FOREGROUND_OR_GEOMETRY_CHANGED');}return{ok:true,path:filename,snapshot:before,capturedAt:new Date().toISOString()};}
  async _dispatch(req){this._authorized(req);const action=req.action;if(action==='status')return{ok:true,available:!this._stopped(req),backend:'gnome-shell-observation',sessionType:(Meta.is_wayland_compositor===undefined||Meta.is_wayland_compositor())?'wayland':'x11',screens:this._screens(),capabilities:{screenshot:true,cursor:true,listWindows:true,mouse:false,keyboard:false,focus:true}};if(action==='screenshot')return this._screenshot(req);if(action==='cursor'){if(this._stopped(req))fail('GUI_LOCAL_STOP');const[x,y]=global.get_pointer();return{ok:true,x,y};}if(action==='listWindows'){if(this._stopped(req))fail('GUI_LOCAL_STOP');return{ok:true,windows:this._rawWindows().map(w=>this._windowRecord(w)).filter(w=>w.handle!=='0')};}if(action==='guard')return{ok:true,snapshot:this._guard(req)};if(action==='focusWindow'){this._guard(req);const windows=this._rawWindows();let matches=[];if(req.handle)matches=windows.filter(w=>this._windowHandle(w)===String(req.handle));else{const q=String(req.titleContains??'').toLocaleLowerCase();matches=windows.filter(w=>String(w.get_title()??'').toLocaleLowerCase().includes(q));}if(matches.length!==1)fail('GUI_WINDOW_SELECTOR_NOT_UNIQUE');matches[0].activate(this._focusTimestamp());await sleep(40);if(global.display.focus_window!==matches[0])fail('GUI_FOCUS_FAILED');return{ok:true,handle:this._windowHandle(matches[0]),backend:'mutter-meta-focus'};}fail('GUI_INPUT_MUST_USE_MUTTER_REMOTE_DESKTOP');}
  InvokeAsync(params,invocation){const[request]=params;let req;try{req=JSON.parse(request);}catch(_){invocation.return_value(new GLib.Variant('(s)',[JSON.stringify({ok:false,error:'GUI_REQUEST_INVALID'})]));return;}this._dispatch(req).then(result=>invocation.return_value(new GLib.Variant('(s)',[JSON.stringify(result)]))).catch(error=>{const m=String(error?.message??error),match=m.match(/GUI_[A-Z0-9_]+/);invocation.return_value(new GLib.Variant('(s)',[JSON.stringify({ok:false,error:match?.[0]??'GUI_NATIVE_FAILED'})]));});}
}
export default class ChatGPTRemoteCommanderExtension extends Extension{enable(){this._service=new Service();this._dbus=Gio.DBusExportedObject.wrapJSObject(IFACE,this._service);this._dbus.export(Gio.DBus.session,'/org/gnome/Shell/Extensions/ChatGPTRemoteCommander');}disable(){this._dbus?.unexport();this._dbus=null;this._service?.destroy();this._service=null;}}
